### ISSUE TITLE
Not working with latest three.js version

### ISSUE THREAD

**Issue by jmeurice** [stevinz/three-wboit#2]
This version of three-wboit doesn't work with newer versions of three.js. The main problem seems to be that the internal workings of shaders in three has been changed. This breaks the custom rendering shader from this project.

Do you plan on continuing support of this library with newer three versions?

**Comment by stevinz** [comment]
I have addressed the shader issues that occurred with the changes to color management in three v152. The library and examples have been updated.

This project isn't my top priority, however, I would like to keep it mostly working. At least until the work by the three.js team is done on the new renderer (node / webgpu)...

**Comment by tom-adsfund** [comment]
@stevinz Will the new renderer have this included then, or do you just mean things will change and so this project won't be the same anymore? I'm trying to get your renderer working with r161, but it's coming up blank when I call WboitPass.render (works with standard render).
