### ISSUE TITLE
outputColorSpace not is WebGLRenderer property

### ISSUE THREAD

**Issue by Davidyanlong** [stevinz/three-wboit#3]
`  function init() {

                renderer = new THREE.WebGLRenderer( { preserveDrawingBuffer: true } );
                renderer.autoClear = false;
                // error
                renderer.outputColorSpace = THREE.SRGBColorSpace;
                document.body.appendChild( renderer.domElement );
`

**Comment by stevinz** [comment]
What version of Three.js are you using? This library was recently updated (to v1.0.14) to use the most recent version of Three.js (i.e. v154). There were [changes made](https://github.com/mrdoob/three.js/releases/tag/r152) in Three.js v152 that include renaming `renderer.outputEncoding ` to `renderer.outputColorSpace`.

If you need to use a version of Three.js prior to v152, try using an earlier release of this library, most likely [v1.0.13](https://www.npmjs.com/package/three-wboit?activeTab=versions). Available remotely from unpkg: "https://unpkg.com/three-wboit@1.0.13/build/index.module.js"
