### ISSUE TITLE
please help me, renderer three layer transparency  artifact

### ISSUE THREAD

**Issue by Davidyanlong** [stevinz/three-wboit#4]
renderer one oit model is  artiface, inner layer dispaly white
// normal renderer
![image](https://github.com/stevinz/three-wboit/assets/10626549/949eedfe-592e-4203-9127-84c6dbf51929)

// enable oit 
![image](https://github.com/stevinz/three-wboit/assets/10626549/0337b203-6f66-4daa-afd5-5783deb7e3d7)

// model file
[oit_testing.zip](https://github.com/stevinz/three-wboit/files/12191116/oit_testing.zip)

// ref
https://playground.babylonjs.com/#WGZLGJ#3348

**Comment by stevinz** [comment]
The Three.js team has made a few internal changes to the renderer over the last couple of versions dealing with transparency and color space. I thought I had made the necessary changes with the last release, but it seems I over looked a few things. 

I have created a few examples of patching the model you supplied with different versions of Three.js. It uses the `WboitUtils.patch()` function on the `StandardMaterial` materials that were created by the gltf loader.

- <a href='https://stevinz.github.io/three-wboit/ModelTest148andUnder.html'>Patching Three v148 and older</a>
- <a href='https://stevinz.github.io/three-wboit/ModelTest149to151.html'>Patching Three v149 to v151</a>
- <a href='https://stevinz.github.io/three-wboit/ModelTest152andUp.html'>Patching Three v152 and newer</a>

These examples have been added to the repo so you can look at the source.

For versions of Three.js 148 and below, the version of this library v1.0.13 should work fine.

For versions of Three.js 149 to 151, you can still use v1.0.13, but you should flag the material `forceSinglePass = true` because of some [changes that were made](https://github.com/mrdoob/three.js/pull/25239) to how Three.js renders double sided transparent objects.

For versions of Three.js 152 and newer you should use v1.0.15 of this library. It takes into account the `renderer.outputColorSpace` setting internally in `WboitPass`.

I should mention, however, there seems to be some issues introduced in Three.js with updating the materials properly. Maybe not the most optimal fixes. But the problems go away by creating new materials by cloning them and disposing of the old ones when changes need to be made, and also by setting `render` on a fixed interval by using `requestAnimationFrame` instead of waiting for the controls to move for a `render` to occur. This is how the last example is set up.

I also added a toggle for `colorSpace` to visualize the difference...

**Comment by Davidyanlong** [comment]
cool!  very thankful！

**Comment by Davidyanlong** [comment]
oh, my God! 
https://unpkg.com/three@0.148.0/build/three.module.js is right  
but https://unpkg.com/three@0.145.0/build/three.module.js is error

**Comment by stevinz** [comment]
It is because in older versions of Three.js transparent, double sided objects are rendered twice. This causes the image to become over-saturated. Try setting the material to 'THREE.FrontSide'. Like this:

```
gltf.scene.traverse((object) => {
    if (object.material) {
        WboitUtils.patch(object.material);
        object.material.side = THREE.FrontSide;
    }
});
```

I updated the [148 example](https://github.com/stevinz/three-wboit/blob/master/example/ModelTest148andUnder.html) in the repo as well.

**Comment by Davidyanlong** [comment]
very thankful!  now correct  display, if three version lower ,  can only set side to Front,  else unnecessary, is right?

**Comment by stevinz** [comment]
That is correct

**Comment by Davidyanlong** [comment]
Sorry to bother you，I have a question for that the postprocess seems artifact in three.js@0.145 in the demo ，would you please offer a demo in lower version，i'll greatly appreciate it.
my test coding
`
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>three.js webgl - order independent transparency</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
        <link type="text/css" rel="stylesheet" href="main.css">
    </head>
    <body>

        <div id="info">
            <a href="http://threejs.org" target="_blank">three.js</a> webgl - weighted, blended order-independent transparency (<a href="http://jcgt.org/published/0002/02/09/">paper</a>, <a href="http://casual-effects.blogspot.com/2015/03/implemented-weighted-blended-order.html">blog</a>)
            <br>See external <a href="https://github.com/stevinz/three-wboit" target="_blank" rel="noopener">three-wboit</a> for more information on order independent transparency.
            <br /><span id="color"></span><br />
        </div>

        <a href="https://github.com/stevinz/three-wboit" class="github-corner" aria-label="View source on GitHub">
            <svg width="80" height="80" viewBox="0 0 250 250" style="fill:#08f; color:#000000; position: absolute; top: 0; border: 0; left: 0; transform: scale(-1, 1);" aria-hidden="true">
                <path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path>
                <path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path>
                <path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path>
            </svg>
        </a>

        
        
        <script async src="https://unpkg.com/es-module-shims@1.3.6/dist/es-module-shims.js"></script>

        <script type='importmap'>
            {
                 "imports": {
                    "three": "https://unpkg.com/three@0.145.0/build/three.module.js",
                    "three/addons/": "https://unpkg.com/three@0.145.0/examples/jsm/",
                    "three-wboit": "https://unpkg.com/three-wboit@1.0.13/build/index.module.js"
                }
            }
        </script>

        <script type="module">

            import * as THREE from 'three';

            import { GUI } from 'three/addons/libs/lil-gui.module.min.js';

            // import { mergeGeometries } from 'three/addons/utils/BufferGeometryUtils.js';

            import { CopyShader } from 'three/addons/shaders/CopyShader.js';
            import { DRACOLoader } from 'three/addons/loaders/DRACOLoader.js';
            import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
            import { GammaCorrectionShader } from 'three/addons/shaders/GammaCorrectionShader.js';
            import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
            import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
            import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
            import { ShaderPass } from 'three/addons/postprocessing/ShaderPass.js';
            import { TexturePass } from 'three/addons/postprocessing/TexturePass.js';

            // // NPM
            // import { MeshBasicShaderMaterial } from 'three-wboit';
            // import { MeshWboitMaterial } from 'three-wboit';
            // import { sRGBShader } from 'three-wboit';
            // import { WboitPass } from 'three-wboit';
            // import { WboitUtils } from 'three-wboit';

            // // Local
            import { MeshBasicShaderMaterial } from '../src/shaders/MeshBasicShaderMaterial.js';
            import { MeshWboitMaterial } from '../src/materials/MeshWboitMaterial.js';
            import { sRGBShader } from '../src/shaders/sRGBShader.js';
            import { WboitPass } from '../src/WboitPass.js';
            import { WboitUtils } from '../src/WboitUtils.js';

            let gl, scene, camera, controls, renderer;
            let composer, clearColor = new THREE.Color();
            let gammaPass, shaderPass, texturePass, wboitPass;

            let ambientLight, directionalLight;
            let bottle, woodTexture, woodMaterial, woodBox, redBox;

            let mouse = new THREE.Vector2();
            let pixelBuffer = new Uint8Array( 4 );

            const params = {
                scene: 'Bottle',
                enabled: true,
                ambient: 1.0,
                background: true,
                gamma: true,
                transparent: true,
                opacity: 0.75,
                weight: 1.0,
            };

            init();
            animate();
            onWindowResize();

            function init() {

                renderer = new THREE.WebGLRenderer( { preserveDrawingBuffer: true } );
                renderer.autoClear = false;
                renderer
                renderer.outputEncoding = THREE.SRGBEncoding;
                document.body.appendChild( renderer.domElement );

                gl = renderer.getContext();

                camera = new THREE.PerspectiveCamera( 50, window.innerWidth / window.innerHeight, 0.10, 100 );
                camera.position.z = 10;
                camera.position.y = - 5;

                controls = new OrbitControls( camera, renderer.domElement );

                // textures

                const textureLoader = new THREE.TextureLoader();

                const backgroundTexture = textureLoader.load( './textures/pz.jpg', ( map ) => {

                    map.colorSpace = THREE.SRGBColorSpace;
                    onWindowResize()

                });

                woodTexture = textureLoader.load( './textures/hardwood2_diffuse.jpg', ( map ) => {

                    map.colorSpace = THREE.SRGBColorSpace;
                    onWindowResize()

                });

                // materials

                woodMaterial = new THREE.MeshBasicMaterial() //new THREE.ShaderMaterial( MeshBasicShaderMaterial );
                woodMaterial.transparent = true;
                woodMaterial.opacity = 0.55;
                woodMaterial.map = woodTexture;
                // woodMaterial.uniforms.opacity.value = 0.75;
                // woodMaterial.uniforms.map.value = woodTexture;

                WboitUtils.patch( woodMaterial );

                // bottle

                bottle = new THREE.Object3D();

                const loader = new GLTFLoader();
                const dracoLoader = new DRACOLoader();
                dracoLoader.setDecoderPath( 'https://unpkg.com/three@0.145.0/examples/js/libs/draco/' );
                loader.setDRACOLoader( dracoLoader );
                // loader.load( './models/scotch.glb', function ( gltf ) {
                    loader.load( './models/oit_testing.glb', function ( gltf ) {

                    // patch materials
                    gltf.scene.traverse((object) => {
                        if (object.material) {

                            WboitUtils.patch(object.material);
                            object.material.side = THREE.FrontSide;

                        }

                    });

                    bottle.add( gltf.scene );
                    gltf.scene.position.y -= 1;

                    updateSceneParameters();

                }, undefined, error => console.error( error ) );

                // // wood

                redBox = new THREE.Mesh( new THREE.BoxGeometry(), new THREE.MeshBasicMaterial( { color: 0xff0000, transparent: true, opacity: 0.5 } ) );
                woodBox = new THREE.Mesh( new THREE.BoxGeometry( 2, 2, 2 ), woodMaterial );
                redBox.visible = false;
                woodBox.visible = false;

                // scene

                scene = new THREE.Scene();

                ambientLight = new THREE.AmbientLight( 0xffffff, 1 );
                directionalLight = new THREE.DirectionalLight( 0xffffff, 1 );
                directionalLight.position.set( 0.5, 0, 0.866 );

                scene.add( ambientLight, directionalLight );
                scene.add( bottle );
                scene.add( redBox, woodBox );

                // background texture pass

                texturePass = new TexturePass();
                texturePass.clear = true;
                texturePass.renderToScreen = false;
                texturePass.map = backgroundTexture;

                const textureRender = texturePass.render.bind(texturePass);
                texturePass.render = function( renderer, writeBuffer, readBuffer /*, deltaTime, maskActive */ ) {

                    textureRender( renderer, readBuffer, writeBuffer ); /* reverse write / read buffers */

                };

                // order independent transparency pass

                wboitPass = new WboitPass( renderer, scene, camera );

                // final render to screen passes

                gammaPass = new ShaderPass( sRGBShader ); /* SRGBColorSpace */
                // gammaPass = new ShaderPass( GammaCorrectionShader ); /* SRGBColorSpace, transparent background, problems on some monitors?? */
                gammaPass.enabled = false;

                shaderPass = new ShaderPass( CopyShader ); /* LinearEncoding */
                shaderPass.enabled = true;

                // effect composer

                composer = new EffectComposer( renderer );
                composer.addPass( texturePass );
                composer.addPass( wboitPass );
                composer.addPass( gammaPass );
                composer.addPass( shaderPass );
                composer.render();

                // gui

                const gui = new GUI();

                const folder1 = gui.addFolder( 'Scene Params' );

                folder1.add( params, 'scene', [ 'Bottle', 'Wood' ] ).onFinishChange( updateScene );
                folder1.add( params, 'ambient', 0, 2 ).onFinishChange( updateSceneParameters );
                folder1.add( params, 'background' ).onFinishChange( updateSceneParameters );
                folder1.add( params, 'gamma' ).onFinishChange( updateSceneParameters );

                const folder2 = gui.addFolder( 'Wboit Params' );

                folder2.add( params, 'enabled' ).onFinishChange( updateSceneParameters );
                folder2.add( params, 'transparent' ).onFinishChange( updateSceneParameters );
                folder2.add( params, 'opacity', 0, 1 ).onFinishChange( updateSceneParameters );
                folder2.add( params, 'weight', 0, 1 ).onFinishChange( updateSceneParameters );

                // events

                window.addEventListener( 'resize', onWindowResize, false );
                renderer.domElement.addEventListener( 'mousemove', onMouseMove );

                // initialize params

                setTimeout( () => updateSceneParameters(), 100 );

                // build scene

                updateScene();

            }

            function updateScene( ) {

                if ( params.scene === 'Bottle' ) {

                    bottle.visible = true;
                    redBox.visible = false;
                    woodBox.visible = false;

                } else {

                    bottle.visible = false;
                    redBox.visible = true;
                    woodBox.visible = true;

                }

                updateSceneParameters()

            }

            function updateSceneParameters() {

                // update ambient light

                ambientLight.intensity = params.ambient;

                // update materials

                scene.traverse( ( object ) => {

                    if ( ! object.material ) return;
                    let materials = Array.isArray( object.material ) ? object.material : [ object.material ];

                    for ( let i = 0; i < materials.length; i ++ ) {
                        const material = materials[ i ];

                        if ( material.isMeshStandardMaterial ) {

                            if ( object.name.includes( 'liquid' ) ) {

                                material.wboitEnabled = false;
                                material.transparent = params.transparent;
                                material.opacity = 0.95;

                            } else {

                                material.wboitEnabled = params.enabled;
                                material.transparent = params.transparent;
                                material.opacity = params.opacity;
                                material.weight = params.weight;
                                material.side = THREE.FrontSide;


                            }

                        } else if ( material.isShaderMaterial ) {

                            material.wboitEnabled = params.enabled;
                            material.transparent = params.transparent;
                            material.weight = params.weight;
                            material.uniforms.opacity.value = params.opacity;
                            material.side = THREE.FrontSide;

                        }

                    }

                } );

                // background

                texturePass.enabled = params.background;
                wboitPass.clearColor = (params.background) ? undefined : clearColor;

                // gamma correction

                // gammaPass.enabled = params.gamma;
                // shaderPass.enabled = ! params.gamma;

            }

            function onWindowResize() {

                camera.aspect = window.innerWidth / window.innerHeight;
                camera.updateProjectionMatrix();

                renderer.setSize( window.innerWidth, window.innerHeight );
                composer.setSize( window.innerWidth, window.innerHeight );

            }

            function onMouseMove( event ) {

                mouse.x = event.clientX;
                mouse.y = event.clientY;

            }

            function animate() {

                requestAnimationFrame( animate );

                render();

                // color under mouse

                gl.readPixels( mouse.x, window.innerHeight - mouse.y, 1, 1, gl.RGBA, gl.UNSIGNED_BYTE, pixelBuffer );

                const rgba = Array.apply( [], pixelBuffer );
                document.getElementById( 'color' ).innerHTML = [
                    ( rgba[ 0 ] / 255 ).toPrecision( 2 ),
                    ( rgba[ 1 ] / 255 ).toPrecision( 2 ),
                    ( rgba[ 2 ] / 255 ).toPrecision( 2 ),
                    ( rgba[ 3 ] / 255 ).toPrecision( 2 )
                ].join( ', ' );

            }

            function render() {

                if ( ! scene ) return;
                 // clear
                 renderer.setClearColor(0.0, 0.0, 0.0);
                renderer.clear();

                composer.render();

            }

        </script>

    </body>
</html>

`
display effect
![image](https://github.com/stevinz/three-wboit/assets/10626549/e723d38d-7b14-4d3f-b0ef-3122be5e4044)

**Comment by stevinz** [comment]
In the function `updateSceneParameters`, change the "update materials" section to this:

```
// update materials

scene.traverse( ( object ) => {
    if ( ! object.material ) return;

    object.material.transparent = params.transparent;

    if ( object.material.isMeshStandardMaterial ) {
        object.material.opacity = params.opacity;
    } else if ( object.material.isShaderMaterial ) {
        object.material.uniforms.opacity.value = params.opacity;
    }

    if ( 'wboitEnabled' in object.material ) object.material.wboitEnabled = params.enabled;
    if ( object.material.wboitEnabled === true ) object.material.weight = params.weight;

} );
```

**Comment by Davidyanlong** [comment]
Admire, admire， I’m got!  very grateful，Hope and you learn more things！

The color diffent, is it because of scene brightness?

![image](https://github.com/stevinz/three-wboit/assets/10626549/7e7c1b64-3b32-4eba-8bc1-f046ac76eaf9)
![image](https://github.com/stevinz/three-wboit/assets/10626549/8b4d69a3-903c-4a23-a097-60282ff45a6f)

**Comment by stevinz** [comment]
That yellow color is coming from the `DirectionalLight` in the scene, try reducing the `intensity` of the light, or removing it from the scene.

**Comment by Davidyanlong** [comment]
If the screen all the time  rendering, a long time, this phenomenon will occur. What is the reason for this?
![image](https://github.com/stevinz/three-wboit/assets/10626549/48ec7c07-78d7-4bee-aeb3-8b0f4ffd53cb)
Just like a grid，this demo is ModelTest148andUnder.html

**Comment by Davidyanlong** [comment]
I updated threejs R157
