### ISSUE TITLE
add WboitPhysicalShader

### ISSUE THREAD

**Issue by Davidyanlong** [stevinz/three-wboit#5]
current have MeshWboitMaterial, Whether to consider increasing MeshStandardMaterial and MeshPhysicalMaterial？

**Comment by stevinz** [comment]
The included `MeshWboitMaterial` is an example of how to incorporate the necessary changes to include weighted, order independent transparency in a Three.js shader. The layout of the other built-in shaders is [available](https://github.com/mrdoob/three.js/tree/dev/src/renderers/shaders/ShaderLib) in the Three.js repo and can be used as a starting point for users to create their own shaders.

I have thought about adding additional shaders to this project, but considering there have been some large changes lately to the rendering system and a lot more to come with the work on WebGPU and the node rendering system, trying to match the `MeshStandardMaterial` or `MeshPhysicalMaterial` uber shaders is beyond the current scope of this project.

While not the cleanest solution, the `WboitUtils.patch()` function should work to patch most materials to allow use with this library. Although the Three.js team seems hesitant to support an imporved material patching workflow, it does work in it's current state, as can be seen in the [patching example](https://stevinz.github.io/three-wboit/PatchMaterials.html).
